version: '3.4'

services:
  catalogdb:
    image: postgres
  distributedcache:
    image: redis
 
  orderdb:
    image: mcr.microsoft.com/azure-sql-edge:latest

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  basketdb:
    image: postgres

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

